server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __hahn__:expired

hahn:
  api-package: com.hahn
  security:
    jwt-key: hahnlis
    token-expired-in: 7200
  order: # 订单配置
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: https://api.hahnlis.top
    pay-callback-path: /v1/payment/wx/notify