server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __hahn__:expired
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）默认是2000ms
      timeout: 2000ms
    cache:
      redis:
        ## Entry expiration in milliseconds. By default the entries never expire.
        time-to-live: 1d
        #写入redis时是否使用键前缀。
        use-key-prefix: true


hahn:
  api-package: com.hahn
  security:
    jwt-key: hahnlis
    token-expired-in: 7200
  order: # 订单配置
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: https://5451-119-131-76-33.jp.ngrok.io
    pay-callback-path: /v1/payment/wx/notify